default: true
MD007: { indent: 2 }
MD013: { line_length: 90, tables: false, code_blocks: false }
MD024: { allow_different_nesting: true }
MD026: { punctuation: '.,;:' }
MD029: { style: 'ordered' }
MD032: false
MD033: false
MD036: false
