site_name: James Couball's Tech Docs
repo_url: https://github.com/jcouball/notes
repo_name: jcouball/notes
edit_uri: edit/main/docs/
site_description: >-
  Technical documentation that the author finds useful in his day to day
  coding activities.

use_directory_urls: true

extra:
    config_override: false
    doc_owner: James Couball
    doc_owner_shortid: jcouball
    doc_owner_email: jcouball@yahoo.com

markdown_extensions:
    - admonition
    - attr_list
    - codehilite
    - def_list
    - markdown_include.include:
          base_path: docs
    - pymdownx.arithmatex
    - pymdownx.betterem:
        smart_enable: all
    - pymdownx.caret
    - pymdownx.critic
    - pymdownx.details
    - pymdownx.inlinehilite
    - pymdownx.magiclink
    - pymdownx.mark
    - pymdownx.smartsymbols
    - pymdownx.superfences:
        custom_fences:
            - name: mermaid
              class: mermaid
              format: !!python/name:pymdownx.superfences.fence_code_format
    - pymdownx.tabbed
    - pymdownx.tasklist:
        custom_checkbox: true
    - pymdownx.tilde
    - toc:
        permalink: true
        toc_depth: 3

plugins:
    - search

strict: true

theme: 'material'

nav:
  - About Me: index.md
  - Documentation Standards: documentation_standards.md

  - AI:
    - ChatGPT Prompt Engineering for Developers: ai/chatgpt_prompt_engineering_for_developers.md
    - Getting Started on Prompt Engineering: ai/getting_started_on_prompt_engineering.md
    - Prompt Engineering Best Practices: ai/prompt_engineering_best_practices.md
    - Prompt Engineering for Improved Performance: ai/prompt_engineering_for_improved_performance.md


  - Git / GitHub:
    - Git Tips: git/git.md
    - Ultimate Git Course:
      - Introduction: git/ultimate_git_course/00_introduction.md
      - Getting Started: git/ultimate_git_course/01_getting_started.md
      - Creating Snapshots: git/ultimate_git_course/02_creating_snapshots.md
      - Browsing History: git/ultimate_git_course/03_browsing_history.md
      - Branching: git/ultimate_git_course/04_branching.md
      - Collaboration: git/ultimate_git_course/05_collaboration.md
      - Rewriting History: git/ultimate_git_course/06_rewriting_history.md

  - Homebrew Tips: homebrew.md
  - Home Files: homefiles.md

  - JavaScript/Node:
    - Ultimate JavaScript Mastery:
      - Types: javascript/ultimate_javascript_mastery/01_types.md
      - Control Flow: javascript/ultimate_javascript_mastery/02_control_flow.md
      - Objects: javascript/ultimate_javascript_mastery/03_objects.md
      - Arrays: javascript/ultimate_javascript_mastery/04_arrays.md
      - Functions: javascript/ultimate_javascript_mastery/05_functions.md
      - Objects Revisited: javascript/ultimate_javascript_mastery/06_objects_revisited.md
      - Prototypes: javascript/ultimate_javascript_mastery/07_prototypes.md
      - Prototypical Inheritance: javascript/ultimate_javascript_mastery/08_prototypical_inheritance.md
      - ES6 Classes: javascript/ultimate_javascript_mastery/09_es6_classes.md
      - ES6 Tooling: javascript/ultimate_javascript_mastery/10_es6_tooling.md

    - Complete Node.js:
      - Introduction: javascript/complete_node_js/00_introduction.md
      - Getting Started: javascript/complete_node_js/01_getting_started.md
      - Node Module System: javascript/complete_node_js/02_node_module_system.md
      - Node Package Manager: javascript/complete_node_js/03_node_package_manager.md
      - Express: javascript/complete_node_js/04_express.md
      - Advanced Express: javascript/complete_node_js/05_express_advanced.md
      - Async JavaScript: javascript/complete_node_js/06_async_javascript.md
      - Crud with Mongoose: javascript/complete_node_js/07_crud_mongoose.md
      - Mongo Data Validations: javascript/complete_node_js/08_mongo_data_validation.md
      - Mongoose Relationships: javascript/complete_node_js/09_mongoose_relationships.md
      - Auth: javascript/complete_node_js/10_auth.md
      - Handling and Logging Errors: javascript/complete_node_js/11_errors.md
      - Refactoring: javascript/complete_node_js/11b_refactoring.md
      - Unit Testing: javascript/complete_node_js/12_unit_testing.md
      - Integration Testing: javascript/complete_node_js/13_integration_testing.md
      - Test Driven Development: javascript/complete_node_js/14_test_driven_development.md
      - Deployment: javascript/complete_node_js/15_deployment.md

  - Mermaid: mermaid.md

  - Music Theory: music_theory.md

  - Ruby:
    - Subprocesses: ruby/subprocesses.md

  - SSL/TLS: ssl_tls.md

  - systemd:
    - Concepts: systemd/concepts.md
    - systemctl: systemd/systemctl.md

  - vscode: vscode.md
