name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  lint_and_build:
    name: Lint and Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v3

      - name: Lint
        run: |
          npm install markdownlint-cli2 --global
          markdownlint-cli2 README.md 'docs/**/*.md'

      - name: Setup Python
        uses: actions/setup-python@v4

      - name: Build
        run: |
          pip3 install -r requirements.txt
          mkdocs build

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: lint_and_build
    if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Deploy
        uses: mhausenblas/mkdocs-deploy-gh-pages@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CUSTOM_DOMAIN: optionaldomain.com
          CONFIG_FILE: mkdocs.yml
          EXTRA_PACKAGES: build-base
          REQUIREMENTS: requirements.txt
